---
# tasks file for ansible-role-win-azcopy
- name: azcopy - Download
  win_get_url:
    url: '{{ azcopy_download_url }}'
    dest: 'C:\Windows\Temp\{{ azcopy_filename_zip }}'
    force: no

- name: azcopy - Unzip
  win_unzip:
    src: 'C:\Windows\Temp\{{ azcopy_filename_zip }}'
    dest: 'C:\Windows\Temp\'
    delete_archive: yes

- name: azcopy - Copy to windir
  win_copy:
    src: 'C:\Windows\Temp\{{ azcopy_unzip_subfoldername }}\{{ azcopy_filename_exe }}'
    dest: '%Windir%\{{ azcopy_filename_exe }}'
    remote_src: yes

- name: azcopy - Delete unzip subfolder
  win_file:
    path: 'C:\Windows\Temp\{{ azcopy_unzip_subfoldername }}'
    state: absent